### ISSUE TITLE
Sticky not working on Cinnamon 20.2: Ties up one core and doesn't display.

### ISSUE THREAD

**Issue by Tater-K7S5A** [linuxmint/sticky#21]
System Info:  https://termbin.com/0h5r5

I upgraded from 20.1 to 20.2 yesterday and when I first launched sticky notes to see what it was it asked to import my Gnotes which I ok'd.  It then launched the note browser and dumped a bunch of stickies on my screen.  I could not figure out how to put the stickies away and the note browser was unresponsive.

I closed the application from the panel and decided I had better make sure Gnotes were ok.  I found that my launcher for Gnotes was gone from my pop out panel and from my menu.  I checked the software manager and found no Gnote application available.  I launched Synaptic and installed Gnote from there.  Then I added a Gnote launcher to my panel and found I had two launchers.  I deleted one.  I was out of time and set the issue aside for later.

Having more time today I launched sticky notes from the menu and found that it launched the browser and dumped the stickies on my screen but I was unable to get the note browser to react to clicks and it was tying up 1 core for an extended period of time.  I killed the process and restarted the application.  This time nothing displayed on the desktop and it still tied up a core.  I rebooted the computer and tried launching sticky from the terminal.  sticky.py is tying up one core and there is no output in the terminal. ctl c does not stop the program and closing the terminal or killing the process through the system monitor is the only way to release the core.

I uninstalled Sticky notes using the software manager, rebooted and the reinstalled the application using the software manager.  Attempting to start the application results in sticky.py tying up one core and nothing appearing on the desktop.  I have to end the process through the system monitor.

I'm happy to provide additional information.

**Comment by collinss** [comment]
Hi @Tater-K7S5A, sounds like something might be corrupted in the note storage file. Try the following in terminal (after making sure sticky notes is not running):
```
gsettings reset org.x.sticky first-run
rm -rf ~/.config/sticky
sticky
```
This will reset everything back to defaults, which will hopefully fix the issue. Then you can try importing from gnote again and see if it happens again. If so, please post any errors in the terminal here so that I can hopefully track down the root cause.

note: this will not affect your original gnote notes in any way as sticky doesn't touch them, it just makes a copy.

**Comment by Tater-K7S5A** [comment]
I followed your instructions.  I was given the dialog to import notes which I answer yes to.  After about 10 minutes sticky.py was still occupying a core and no output is showing in the terminal: The cursor moved down one line and is just sitting there.

I ended the process and ran the commands again.  This time when offered the option to import my notes I declined.  The application started and showed the manager an a blank sticky.

Is it possible that one or more of my existing notes may be too large to be imported?  

Also:  Is there no way to minimize/hide the stickies?  Or, do you simply have to close the app if you want/need them out of view?

Thank you for the assistance.  I think I will find a use for the stickies, but they probably won't work as a replacement for gnote.  I see the use cases as different.

**Comment by collinss** [comment]
> no output is showing in the terminal

I was afraid that might be the case. It will be much harder to track down the problem without an error message.

> Is it possible that one or more of my existing notes may be too large to be imported?

It's possible I suppose, but I imagine it would have to be _really_ big. I'd sooner suspect a bug in the code that's causing it to go into an endless loop.

>  Is there no way to minimize/hide the stickies?

Yes, there are 2 different ways to accomplish this. The first is to click on the tray icon (I believe this is currently enabled by default, but if not, you can enable it in preferences). The second is to enable the setting to show in the taskbar (also available in preferences, but I'm pretty sure that one isn't enabled by default).

> they probably won't work as a replacement for gnote.

No, that wasn't really the intent (at least not right now). Gnote is designed for a very specific sort of workflow and I think it does that fairly well, but it doesn't really work for other workflows. For many, a note taking app is most useful when you can see it right there on the desktop, or just jot something down really quickly, and for those types of workflows, gnote just doesn't cut it. And while we did try to make sure sticky could do pretty much everything that gnote can (though not always in the same way), the workflow just isn't going to be the same. For those who really like the gnote workflow, it's probably still the best option, and we generally recommend sticking with that for the time being, though we do have some ideas for how we might introduce a gnote-like workflow into the manager in the future, so stay tuned!

**Comment by Tater-K7S5A** [comment]
> > no output is showing in the terminal
> 
> I was afraid that might be the case. It will be much harder to track down the problem without an error message.

I am willing to pull whatever logs may be helpful.  

> > Is it possible that one or more of my existing notes may be too large to be imported?
> 
> It's possible I suppose, but I imagine it would have to be _really_ big. I'd sooner suspect a bug in the code that's causing it to go into an endless loop.
 
I just checked the notes and none are _huge_.  The biggest is 9488 characters.  It's a ZFS error message I am trying to parse.

> > Is there no way to minimize/hide the stickies?
> 
> Yes, there are 2 different ways to accomplish this. The first is to click on the tray icon (I believe this is currently enabled by default, but if not, you can enable it in preferences). The second is to enable the setting to show in the taskbar (also available in preferences, but I'm pretty sure that one isn't enabled by default).

The tray icon is too elegant for me to have found on my own.  I right clicked it looking for something in the context menu.
I have been playing with it as I write this and will be posting another issue.  The toggle seems to be conditional when it shouldn't be.  I think.  Maybe.

> > they probably won't work as a replacement for gnote.
> 
> No, that wasn't really the intent (at least not right now). Gnote is designed for a very specific sort of workflow and I think it does that fairly well, but it doesn't really work for other workflows. For many, a note taking app is most useful when you can see it right there on the desktop, or just jot something down really quickly, and for those types of workflows, gnote just doesn't cut it. And while we did try to make sure sticky could do pretty much everything that gnote can (though not always in the same way), the workflow just isn't going to be the same. For those who really like the gnote workflow, it's probably still the best option, and we generally recommend sticking with that for the time being, though we do have some ideas for how we might introduce a gnote-like workflow into the manager in the future, so stay tuned!

I definitely have a use for stickies and I am grateful for your efforts on this.  I think Mint's decision to swap one out for the other puts them in opposition when they really are for two different types of notation:  Notebook vs. Sticky.

Let me know if I can pull any logs or try some experiments for you.

**Comment by collinss** [comment]
> I just checked the notes and none are huge. The biggest is 9488 characters. It's a ZFS error message I am trying to parse.

Yeah, that doesn't sound big enough to cause problems. I suppose it could be something in the error message that's messing up the parsing function, though I would expect there to at least be an error message in the terminal in that case.

> Let me know if I can pull any logs or try some experiments for you.

Thanks, I'll keep that in mind! In the mean time, I'm going to have to do some digging and see if I can find a likely culprit. If anything comes up I'll post some .deb files here for you to try.

>  The toggle seems to be conditional when it shouldn't be.

Yes, I know about that one already. I've 'fixed' it several times but it keeps coming back. I'm starting to wonder if it might be a bug in the window manager.

**Comment by collinss** [comment]
Hi @Tater-K7S5A , I have a [.deb](https://github.com/linuxmint/sticky/files/6820092/sticky_test.zip) for you to try. I added some extra logging, so that hopefully we can track down exactly where the issue is happening. It also includes a positioning fix that may or may not be related. You'll need to reset everything like before, install the deb, run the app from a terminal, then let me know how far you get in the output (it will spit out some file names at some point in the process, but you don't need to include them if you don't want to; they're just to identify if there's a particular file it's getting hung up on). If you have notes you don't want to lose, you can temporarily copy `~/.config/sticky/notes.json` to another location, and then move it back when you're done.

**Comment by Tater-K7S5A** [comment]
Thank you @collinss  

I uninstalled Sticky and had to manually remove the json file to try to get an clean install (It wasn't removed when I purged the prior Sticky install and it kept bringing up the existing note.) After I installed the new deb it starts without the import dialog starting.

I looked for a json from gnotes in my home directory but nothing came up, so I don't have an auto import nor have I found what I would need to do a manual import.  As I tried additional searches, Nemo search now has decided to not work.  (It has never been very reliable, I'm afraid) I rebooted and it still is finding nothing.  As in:  No file found even if I am looking at the file when I type in the name.  I will need to research how to reset Nemo search and get it working again.

The terminal output has been:

~$ sticky
loading notes
loading note:  0
^CTraceback (most recent call last):
  File "/usr/lib/sticky/sticky.py", line 952, in <module>
    sticky.run()
  File "/usr/lib/python3/dist-packages/gi/overrides/Gio.py", line 44, in run
    return Gio.Application.run(self, *args, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/lib/python3/dist-packages/gi/_ossighelper.py", line 251, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt

On the positive side, the toggling of notes seems to be fixed! 

I will try to work on this some more when I get home tonight or in the morning.  Thank you again.

**Comment by mtwebster** [comment]
@Tater-K7S5A Do you have case-sensitivity and/or folder recursion turned on for search in nemo? There's really no 'reset' for search.

As for sticky, can you try something for me:

```
# install debugger
apt install gdb
# run sticky with debugger (make sure you've killed any existing process of it first)
gdb --args python3 /usr/lib/sticky/sticky.py
# let it run until you're sure it's well into its non-responsive state.
# Then ctrl-c to halt the program
# generate a core dump file - you may get warnings, that's ok.
(gdb) generate-core-file
# exit debugger
(gdb) q
# There should be a file in the current folder named 'core.<process id>'
```
Please attach that resulting file (You may need to zip it up for github to accept it)

Thank you

**Comment by collinss** [comment]
@Tater-K7S5A in order to get the import dialog to pop up again you'll need to run 
```
gsettings reset org.x.sticky first-run
```

**Comment by Tater-K7S5A** [comment]
@collinss I ran the reset code and started sticky in the terminal.  The import dialog came up and I selected import.  The manager opened and some of my notes appeared.  Group 1 was highlighted.  I then selected Archives which loaded some more and then current which showed more then I tried to click unfiled which did not select and froze the manager.  

sticky.py locked on to 100% of one core of my CPU and 99.7 Mib of ram.

`~$ sticky
import started
importing file  /home/hal/.local/share/gnote/94faedf2-b1a3-4302-9e9a-998795178a87.note
importing file  /home/hal/.local/share/gnote/b8d3beee-521d-4203-8a21-950e0a6d8537.note
importing file  /home/hal/.local/share/gnote/e50aa135-c0e0-4bed-b2a7-90fefde7c77e.note
importing file  /home/hal/.local/share/gnote/81fc9b36-1a26-4f71-bb53-334d0b93b1c7.note
importing file  /home/hal/.local/share/gnote/851db39e-e3ef-443a-9837-4680e82e1184.note
importing file  /home/hal/.local/share/gnote/566e70ff-0526-41ae-9407-248a94357e36.note
importing file  /home/hal/.local/share/gnote/f70bbd95-7c05-471d-bef0-7277d1b023cf.note
importing file  /home/hal/.local/share/gnote/9fc3dbfc-2732-43c1-a777-3190016f47fc.note
importing file  /home/hal/.local/share/gnote/2a9481b6-626f-41f4-ac90-470f35f0d38e.note
importing file  /home/hal/.local/share/gnote/84665eed-6d16-451f-8c34-8a165882e285.note
importing file  /home/hal/.local/share/gnote/15a4f0dc-5dd5-4fa3-942a-2bdfb8dd38db.note
importing file  /home/hal/.local/share/gnote/5ea46c51-51cf-45df-936d-b671016afe9d.note
importing file  /home/hal/.local/share/gnote/cd0a85aa-0105-4fca-a911-cbe31c768644.note
importing file  /home/hal/.local/share/gnote/342cb8ee-60c9-4346-9c4f-66ac6f8fd64d.note
importing file  /home/hal/.local/share/gnote/0b1d0b8d-8499-4ec2-af59-c9742f8a3d8f.note
importing file  /home/hal/.local/share/gnote/9684f9f3-0c45-47df-907a-17e02e64a8f8.note
importing file  /home/hal/.local/share/gnote/59bf5a2a-e337-41e1-9f52-f4dd0c81d59b.note
importing file  /home/hal/.local/share/gnote/7cd0f2a2-0f0b-45cc-9437-fe66431b6bc0.note
importing file  /home/hal/.local/share/gnote/46f66ce7-78ad-471c-b943-fbc19c6a3cf5.note
importing file  /home/hal/.local/share/gnote/548939a0-2ca4-430f-933f-baedba4fb31b.note
importing file  /home/hal/.local/share/gnote/df57ec28-b2b3-4353-b747-f1a78058cc42.note
importing file  /home/hal/.local/share/gnote/4b585f28-51e3-4293-99b6-0b0a061801c8.note
importing file  /home/hal/.local/share/gnote/2956599f-20d5-4d51-9dc0-7444171fe005.note
importing file  /home/hal/.local/share/gnote/ff408510-b08b-48e5-b016-3fe38b7f207b.note
import done
loading notes
loading note:  0
loading notes
loading note:  0
loading note:  1
loading note:  2
loading notes
loading note:  0
loading note:  1
loading note:  2
loading note:  3
loading note:  4
loading notes
loading note:  0
loading note:  1
loading note:  2
loading note:  3
loading note:  4
loading note:  5
Terminated
`

**Comment by Tater-K7S5A** [comment]
@mtwebster I am going to have to do a deep dive into the search, as it is not actually searching just throwing up a "nothing found".  Maybe tomorrow morning when I am off work.  I have been trying to follow up on this in the morning while I eat breakfast before I go to work so I have less than an hour each day to work at it.

I tried to run the debug but when I tried "generate-core-file" the response was "You can do that without a process to debug."  

Obviously, I have missed the turning.  It also occurs to me that I have no idea what you mean by "current folder" (My home directory?  The directory the terminal is operating in?) and I can't do any searches so I can't really run that down if I could get the file to generate.  sigh.

**Comment by Tater-K7S5A** [comment]
@collinss It occurred to me that I should restart sticky and see if it would load and what the errors/output were.  It did not start and the sticky.py immediately grabbed a core and 47.2 Mib of ram.
```
~$ sticky
loading notes
loading note:  0
loading note:  1
loading note:  2
loading note:  3
loading note:  4
loading note:  5
Terminated


```

**Comment by mtwebster** [comment]
@Tater-K7S5A I meant the folder your terminal was in when you ran the commands (probably your home folder).

Does sticky terminate itself after a while? Or are you killing it? For my debug steps to work, you need to ctrl-c (break) while it's still running, then generate-core-file.


As for nemo, did you check the state of these buttons?
![image](https://user-images.githubusercontent.com/262776/125953717-f23cce80-9b95-4957-9a8d-96d89b362054.png)

The top row, if Aa is active, searching for 'foo' will not find 'Foo'. If the bent arrow button is set, the search will enter subfolders of the current location. Only the folder you activated search in will be checked.

Thanks for working with us to try and fix this sticky issue.

**Comment by collinss** [comment]
It looks like the import script is working fine. If it didn't occur until after you selected the unfiled group then there's probably something in that group that's causing the issue. That actually narrows it down a bit, but lets make sure it's just that group first by runing `gsettings reset org.x.sticky active-group` in the terminal, then try selecting all the groups again (maybe leave the unfiled group for last so we can see if there are any others that do it too).

Also open gnote and tell me how many notes are in the unfiled group. It seems like it's getting hung up on the 6th note in that group, so that's where we want to look first.

Finally, if you could open up the file `~/.config/sticky/notes.json` in a text editor, and scroll down to the line where the unfiled group is defined (should look like `"unfiled": [`). Beneath that you should see a series of blocks of lines with curly braces around them. If you count out the sixth block, that will give you all the info for that note. Then, if you don't mind, copy/pastebin that block here so that I can (hopefully) identify and fix the issue.

**Comment by Tater-K7S5A** [comment]
> @Tater-K7S5A I meant the folder your terminal was in when you ran the commands (probably your home folder).
> 
Thank you, I am fairly ignorant of how things work under the hood in Linux.  I've only been muddling about in it for a couple years.

> Does sticky terminate itself after a while? Or are you killing it? For my debug steps to work, you need to ctrl-c (break) while it's still running, then generate-core-file.
> 
Due to the short window I have had available I have been killing it after things seemed to have stopped.  I just tried to run the debugger again and gdb returned "(No debugging symbols found in python3)"  which is new.  But there is no sign that sticky was called.

> As for nemo, did you check the state of these buttons?
> ![image](https://user-images.githubusercontent.com/262776/125953717-f23cce80-9b95-4957-9a8d-96d89b362054.png)
> 
> The top row, if Aa is active, searching for 'foo' will not find 'Foo'. If the bent arrow button is set, the search will enter subfolders of the current location. Only the folder you activated search in will be checked.
> 
I just tried searching home again and it is now giving results.  The system has been rebooted a couple ties in the past day, so maybe it just needed to have a fresh start.

> Thanks for working with us to try and fix this sticky issue.
I just hope that I am actually adding value and not tying your time up with my fumbling through the process.

**Comment by Tater-K7S5A** [comment]
> It looks like the import script is working fine. If it didn't occur until after you selected the unfiled group then there's probably something in that group that's causing the issue. That actually narrows it down a bit, but lets make sure it's just that group first by runing `gsettings reset org.x.sticky active-group` in the terminal, then try selecting all the groups again (maybe leave the unfiled group for last so we can see if there are any others that do it too).

The response was exactly the same.  Loading note:  5 and lock up.  I looked inside note 6 and note 5 using Gnote.  Note 6 is only a few words.  What I found with note 5 is that a block of the text was stored in a selected state (Highlighted).  I unselected that text and ended sticky.py  then started again.  The result was the same.

> 
> Also open gnote and tell me how many notes are in the unfiled group. It seems like it's getting hung up on the 6th note in that group, so that's where we want to look first.

Eight notes are in the "Unfiled" group in Gnote.  After checking the json file from Sticky I find these notes do not match the Gnote notes:  _The contents of the groups do not match_.
 
> Finally, if you could open up the file `~/.config/sticky/notes.json` in a text editor, and scroll down to the line where the unfiled group is defined (should look like `"unfiled": [`). Beneath that you should see a series of blocks of lines with curly braces around them. If you count out the sixth block, that will give you all the info for that note. Then, if you don't mind, copy/pastebin that block here so that I can (hopefully) identify and fix the issue.

The sixth block is
`  {
            "title": "ata softreset failed (device not ready)",
            "text": "ata softreset failed (device not ready) \n\nPer Void Linux Wiki, you can get rid of this warning by adding libata.force=norst to your kernel parameters or compile your kernel with CONFIG_SATA_PMP=n.\n\nObviously I'm not recompiling my kernel\n\n#tag:link:https://wiki.voidlinux.org/Frequently_Asked_Questions#How_to_get_rid_of_.22ataN:_softreset_failed_.28device_not_ready.29.22_.3F#tag:link:\n\nInteresting ideas for updating kernel parameters:\n\n#tag:link:https://askubuntu.com/questions/19486/how-do-i-add-a-kernel-boot-parameter#tag:link:\n\n#tag:link:https://kerneltalks.com/linux/how-to-tune-kernel-parameters-in-linux/#tag:link:\n\nFirst things, first:  Replace/reseat the ATA cables to RAID and see if it fixes the issue.\n",
            "color": "yellow",
            "x": 260,
            "y": 260
        },`

**Comment by Tater-K7S5A** [comment]
@collinss Just to make sure that I have given you everything:  After the sticky.py process freezes and I end it through the system monitor it will not launch the manager or notes when run.  It gives the following output:
`~$ sticky
loading notes
loading note:  0
loading note:  1
loading note:  2
loading note:  3
loading note:  4
loading note:  5
`
and has to be ended through the system monitor.  (ctl+c doesn't work and I don't know how else to stop the application if you are wondering why I'm doing it that way.)  If I use the `gsettings reset org.x.sticky active-group` command then it starts again normally.  I assume this is because Sticky is trying to pick up where it left off when ended (opening unfiled) and is getting stuck again.  I just wanted to make sure I had shared as much as I could.

**Comment by collinss** [comment]
Yup, it's definitely something in that note. I can reproduce the freeze as well.

**Comment by collinss** [comment]
@Tater-K7S5A , can you see if this fixes the issue for you?
[sticky_deb.zip](https://github.com/linuxmint/sticky/files/6834951/sticky_deb.zip)

You'll need to remove the notes.json file and re-run the import for it to work, but it should fix the issue.

**Comment by Tater-K7S5A** [comment]
@collinss Thank you!  That appears to have solved it.  What was in my note that was causing the issue?

**Comment by collinss** [comment]
The problem was that I use '#' in the internal note format to mark formatting and such, but I forgot to escape them during import from gnote, so when it encoutered a "#" in the note it proceeded as though it was formatting, but it glitched and entered an infinite loop.
