### ISSUE TITLE
Issue: Note application is closing when pressing CTRL+X and then CTRL+V!

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/sticky#27]
Note application is closing when pressing **CTRL+X** (to cut some of the text content) and then **CTRL+V** (to paste the content into the same note). This closure did not happen when pasting content from another location and also did not happen if the text was copied or cut from another note.

I'm currently using Linux Mint 20.2 Uma and my notebook is an Intel 250 G6, with almost 4G RAM. If needed, I can send you more detailed specifications.

**Comment by collinss** [comment]
I can't seem to reproduce this. Can you make sure the application is completely closed (if you use the tray, you'll need to select quit from the context menu), run it from a terminal (type "`sticky`" from the command prompt), and then see if anything is output into the terminal when you cause the crash?

**Comment by anaximeno** [comment]
I ran it from a terminal, and this problem only seems to happen when there are many characters/words in the note. When the error occurred this was the output from the terminal:

> (sticky.py:59003): Gtk-WARNING **: 02:48:09.554: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators
/usr/bin/sticky: line 3: 59003 Segmentation fault  (core dumped) /usr/lib/sticky/sticky.py $*

**Comment by collinss** [comment]
Ah, ok, I think I know what's going on there, and if I'm right, it's already fixed here on github, but hasn't made it in a release yet. If you want, you can try building from source, or wait until the next update lands in the update manager (hopefully in the next few days).

**Comment by anaximeno** [comment]
Yes, I found a similar issue which was closed by you #25, I believe that will solve my problem too, so I'll wait until the next update. Thank you for your support!
