### ISSUE TITLE
Option to import gnotes seems to import TomBoy notes

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/sticky#29]
I ran the app (version 1.2) for the first time. I was asked whether I wished to import any 'gnotes'. I was unsure whether I had ever run the application 'gnote' on the PC at issue, but I said yes. The result was a couple of notes that seemed to have been imported from the _TomBoy_ notes application. For, those notes were about how to use TomBoy. So something seems wrong or confusing here.

**Comment by collinss** [comment]
Gnote is a fork of TomBoy, and uses the same format. The difference is that gnote is still under active development while Tomboy is not. I suppose we could clarify that in the import dialog, but I don't know if it's worth it since tomboy seems to be dead (for several years).
