### ISSUE TITLE
The app works poorly with the dock called 'Plank'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/sticky#30]
This may be a problem with Plank rather than with Sticky, though Plank does not usually have the sort of problem at issue here (though it does sometimes have the problem with the program Rainlendar - but Rainlendar is a poorly-written program).

I ran Sticky (version 1.2). A window appeared and an icon appeared on Plank (version '0.11.89 RELEASE') and a (rather nice) tray icon appeared. So far, so good.

Upon closing the aforementioned window, the icon for Sticky persisted within Plank and indeed Plank marked the app as running. But - and this is the problem - clicking that icon, or scrolling the mouse wheel over that icon, did nothing; in order to do anything further with Sticky, I had to use the tray icon.

Desirable behaviour: either Plank should show no icon at all (which would not be ideal) or (better) Plank would show the icon and clicking that icon (or scrolling the wheel over the icon) would do something (though I am unsure what).

I realise that Plank is not built into Mint, and that at least many of the previously numerous problems with GWL have been fixed. (It was those problems that pushed me to use Plank.) Still: it would be good were Sticky to work well with Plank. Indeed perhaps Sticky has problems with other docks. (I have not tested it with any other dock.)

**Comment by collinss** [comment]
I believe the issue is with plank. Unless you changed the Show in taskbar setting in the preferences window, it shouldn't be showing that window. This means that Plank is improperly ignoring a window hint.

**Comment by LinuxOnTheDesktop** [comment]
@collinss 

Thank you. I have [filed a bug report with plank](https://bugs.launchpad.net/plank/+bug/1936979), though sadly in my experience so to do is to shout into the void.
