### ISSUE TITLE
One pixel in the upper left hand corner when sticky is running.

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/sticky#31]
Issue is solid repeatable on both of these systems whether sticky is run from the command line or the start menu.  See attached enlarged screenshot of the one pixel.  Issue beings when sticky is started and ends when sticky is quit.  Using the latest version of sticky: 1.2  Current on all other updates.
It occurs on two systems, info below.  Note: You won't notice it with a light background.

WM Theme: Linux Mint (Mint-X) 
Theme: Mint-X-Aqua [GTK2/3] 
Cinnamon 5.0.5 wm: muffin 5.0.1
NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 470.57.02
resolution: 1920x1080~60Hz

WM Theme: Linux Mint (Mint-X)
Theme: Mint-X-Aqua [GTK2/3]
Cinnamon 5.0.5 wm: muffin 5.0.1
NVIDIA GP108 [GeForce GT 1030] driver: nvidia v: 460.80
resolution: 1920x1080~60Hz, 1920x1080~60Hz

xsession-errors:
Cjs-Message: 07:54:45.410: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: sticky (:1.19797/org/x/StatusIcon/Icon)
Cjs-Message: 07:55:13.560: JS LOG: [LookingGlass/info] Removing XAppStatusIcon: sticky (:1.19797/org/x/StatusIcon/Icon)

![Screenshot-from-2021-07-24-07-40-53](https://user-images.githubusercontent.com/45599505/126867699-57a7b471-b5d5-4727-bb4f-d640ab47c3c7.png)

**Comment by Harry-W-Haines-III** [comment]
Was anyone else able to duplicate or verify this issue with a dark desktop?

**Comment by xenopeek** [comment]
This is a continuation of #26. It was assumed to only affect Xfce but yes I can confirm this affects Cinnamon as well.

It's a 1x1 dummy window, so that Sticky can respond to window management events, that should be off-screen.

**Comment by li20034** [comment]
I know this is an edge case, but for low end hardware, like what I'm using, disabling the XFCE (xfwm) compositor can improve performance quite a bit. In this case, enabling transparency on the dummy window just makes the white pixel turn black; it's still visible.

**Comment by collinss** [comment]
@li20034 I agree, this is not the ideal solution I was hoping for. Unfortunately, (as far as I can tell) the bug is a result of the window manager trying to be smart and moving the window back on screen. Nothing I've tried has succeeded in overriding the window manager on this, so I'm not sure what else to do. I'm not sure there is anything that can be done to prevent the window from being moved back on screen short of patching the window manager directly (which is really not realistic).

**Comment by Harry-W-Haines-III** [comment]
Made the changes to the two files per what was changed in GitHub.  At least for me, on Cinnamon 5.0.5 wm: muffin 5.0.1 and these displays, the issue was fixed.  Have been using Sticky every day since.
