### ISSUE TITLE
Feature request: add the option to open the notes by double-clicking on the tray icon when the main window is closed

### ISSUE THREAD

**Issue by pxcandeias** [linuxmint/sticky#32]
Hello all,

I find that after closing the main window I cannot reopen it by double clicking on the tray icon. I would expect this to be a standard behaviour, since the tray icon is still active, instead of having to left click the mouse to access the context menu.

I think this could be a nice addition to improve its usability.

BR,
Paulo

**Comment by collinss** [comment]
You can now open the main window by middle clicking the tray icon (or use left and right mouse buttons at the same time if you have middle click emulation enabled).
