### ISSUE TITLE
AttributeError: 'gi.repository.XApp' object has no attribute 'StatusIcon'

### ISSUE THREAD

**Issue by ryanfortner** [linuxmint/sticky#42]
After following compile instructions from [here](https://github.com/linuxmint/sticky#mint-debian-ubuntu-and-derivatives), I receive the following error.

Here is the terminal output:
```
$ sticky
Traceback (most recent call last):
  File "/usr/lib/sticky/sticky.py", line 603, in do_activate
    self.create_status_icon()
  File "/usr/lib/sticky/sticky.py", line 683, in create_status_icon
    self.status_icon = XApp.StatusIcon()
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 132, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.XApp' object has no attribute 'StatusIcon'
```

Any suggestions as to what may have caused this?

**Comment by Crilum** [comment]
Me too.

**Comment by mtwebster** [comment]
Please check out the README, your version of xapps is too low: https://github.com/linuxmint/sticky/blob/master/README.md#runtime-deps

**Comment by Crilum** [comment]
Well, I installed this: [http://ftp.us.debian.org/debian/pool/main/p/python-xapp/python3-xapp_2.0.2-2_all.deb](http://ftp.us.debian.org/debian/pool/main/p/python-xapp/python3-xapp_2.0.2-2_all.deb)
This is my xapp version:
```
python3-xapp/now 2.0.2-2 all [installed,local]
```

**Comment by mtwebster** [comment]
There's a c library xapps - I don't know what debian base you're on, but buster's version is too low. You can try the packages here: http://packages.linuxmint.com/search.php?release=debbie&section=any&keyword=xapp which may work, but you'd be better off building it.

**Comment by Crilum** [comment]
I'm on debian buster, and the .deb I installed was for bullseye. the package name is `python3-xapp`.

**Comment by mtwebster** [comment]
That's not the one causing the issue.
```
gir1.2-xapp-1.0 (>= 1.6.0)
```
You need that, plus its dependencies. On buster those packages are not new enough. This is why I linked the other packages.

**Comment by Crilum** [comment]
Ok, thanks. I think I can download all of those from the bullseye repository.
