### ISSUE TITLE
dpkg erro cannot access archive sticky*.deb

### ISSUE THREAD

**Issue by JonMuadDib** [linuxmint/sticky#43]
So after following the instruction, I get the following error. 

dpkg: error: cannot access archive 'sticky*.deb' : No such file or directory. 

Everything when smooth, until  the last step to install. Is there something I missing to do.

**Comment by JosephMcc** [comment]
Make sure that you changed directories after you were done building. The .deb files will be one directory up.

**Comment by JonMuadDib** [comment]
Thanks for the reply. I will start from the beginning.
