### ISSUE TITLE
Does not install on linux mint 20.1 xfce edition

### ISSUE THREAD

**Issue by brunoais** [linuxmint/sticky#45]
I can compile but I cannot install on linux mint 20.1 xfce edition.

The offending installations are `gir1.2-xapp-1.0` and `python3-xapp`

```
dpkg: dependency problems prevent configuration of sticky:
 sticky depends on gir1.2-xapp-1.0 (>= 2.2.0); however:
  Version of gir1.2-xapp-1.0 on system is 2.0.7+ulyssa.
 sticky depends on gir1.2-gspell-1; however:
  Package gir1.2-gspell-1 is not installed.
 sticky depends on python3-xapp (>= 2.2.0); however:
  Version of python3-xapp on system is 2.0.2.
```

How to install in those systems?

**Comment by collinss** [comment]
Unfortunately, sticky relies on code that was introduced in a newer version of xapp. If you would like to install sticky, I would recommend upgrading your system to 20.2 via the update manager. The upgrades between versions of the 20.x series are easy and quite safe. Alternatively you could build newer versions of dependencies like xapp, but there's more chance that something goes wrong that way.

**Comment by brunoais** [comment]
@collinss Would it be solved if this was packaged as flatpak?

**Comment by collinss** [comment]
Probably
