### ISSUE TITLE
Multiple colors in a same group

### ISSUE THREAD

**Issue by Christian-V** [linuxmint/sticky#47]
It would be nice and useful to be able to choose individually the colour of each note (among those proposed by default for the groups), for example to highlight urgent or essential informations.
This is especially true when you use, like me, Sticky Notes with only one group to have information displayed all the time, either so you don't forget them, or because they are simple and of very common use.
The more developed information being transferred to a hierarchical notes tool, possibly with a brief reminder in Sticky Notes.

**Comment by xenopeek** [comment]
You can click the droplet icon in the top left corner of a note to choose its color. Is that what you're looking for or am I misunderstanding your feature request?

![image](https://user-images.githubusercontent.com/21159972/146224810-abd2fd4f-4930-4252-8ce4-628c9f220d58.png)

**Comment by haggen88** [comment]
It is possible to change the colors of the notes. By default it is yellow, but it can be changed in Preferences / Notes / Default color. 

![s](https://user-images.githubusercontent.com/68134588/146255444-23e25931-e509-4983-b451-a11e72c3daf7.png)

**Comment by Christian-V** [comment]
Pardon, c'est ce que je voulais.
Je n'avais pas fait attention à la "goutte" à gauche des notes. Je pensais que seuls les groupes   pouvaient avoir une couleur propre.
