### ISSUE TITLE
Pasting a sentence with a spelling mistake is written backwards

### ISSUE THREAD

**Issue by Matgc04** [linuxmint/sticky#94]
Kernel: Linux 5.15.0-58-generic x86-64 Linux Mint 21 Vanessa
xfce4-about 4.16.1
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)
LANG="es_AR.UTF-8"

The problem happens when i copy a string that has a word marked as wrong by the notes' spell-checker. It only happens if the text is pasted into the same note that was copied from. 
Here's an example of what happens: 
¿se define dinamicamente (last word is missing an accent)
gets pasted to 
dinamicamente¿se define
This only happens in the same note(copying a wrong sentence to any other thing will be ok) and if i mark the troubled words to be ignored the problem disappears. Originally the spell checker was set to spanish AR but it is the same problem with every different language (only checked dialects in spanish, with different languages just the plain version)

**Comment by collinss** [comment]
What is your version of Sticky? You can check in the about dialog. If it's less than 1.14, try updating to that version. I fixed a bug between 1.13 and 1.14 that sounds very much like what you're experiencing.

**Comment by collinss** [comment]
Glad to hear it!
