### ISSUE TITLE
Outdated license address and possibly mismatching license

### ISSUE THREAD

**Issue by paseaf** [linuxmint/sticky#96]
**Outdated license address**
I'm trying to build RPM package for sticky, but there was an error  [`incorrect-fsf-address`](https://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address).
Turns out the current license address does not match with https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

**Mismatching license?**
In Readme it says the license is `GPLv2`, but the `COPYING` file seems like the older version of [LGPLv2.0](https://www.gnu.org/licenses/old-licenses/lgpl-2.0.en.html)

I would love to submit a PR to update the license, but I'm not sure if it should be GPLv2 or LGPLv2. Does anyone know it?

**Comment by clefebvre** [comment]
Hi @paseaf, it should be GPLv2 afaik. COPYING looks wrong.
