### ISSUE TITLE
Better icon

### ISSUE THREAD

**Issue by morciej** [linuxmint/sticky#99]
I think the attached status icon plays better with other xapps. The one in repositories is a bit too bold. It sticks out like a sore thumb. I am using Ver. 1.14 with Linux Mint 21/xfce.

New icon svg file:

![sticky-symbolic](https://user-images.githubusercontent.com/17895139/222637104-23fb344e-651e-41fe-85df-2ba8b5237aed.svg)

Here's how the new one shows on my panel:

![Panel Screenshot](https://user-images.githubusercontent.com/17895139/222637695-80cce945-608f-4822-a172-192b2b26e5aa.png)

**Comment by clefebvre** [comment]
Current one for comparison: 
![image](https://user-images.githubusercontent.com/1138515/222811449-e70c90a4-d5c5-4f44-96b3-f6fc4d0d4e4f.png)

**Comment by collinss** [comment]
@morciej Thanks, that looks nice! Could you make a pull request for it (proper attribution and all)?

**Comment by morciej** [comment]
Done. My first pull request!

**Comment by collinss** [comment]
Thanks, and congrats on your first pr!
